stages:
  - test
  - build
  - docker

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mkdir -p ~/.m2
    - echo "<settings><servers><server><id>github</id><username>zarequiem</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
    - mvn test
  only:
    - develop

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mkdir -p ~/.m2
    - echo "<settings><servers><server><id>github</id><username>zarequiem</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - develop

docker:
  stage: docker
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:latest
  only:
    - develop