apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: devops-l3gl
type: Opaque
stringData:
  mysql-root-password: root1234

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: product_db

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: devops-l3gl
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP